services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTRGES_DB: nest
    networks:
      - test
networks:
  test: